name: Backend CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use the latest stable Node.js
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm install -g pnpm@9.10.0

      - name: Install Dependencies
        run: |
          cd backend
          pnpm install --frozen-lockfile

      - name: Run Build
        run: |
          cd backend
          pnpm run build

      - name: "Run tests"
        run: |
          cd backend
          pnpm run test

      - name: "Run Format Check"
        run: |
          cd backend
          pnpm run prettier:check
